rpc: https://rpc.beaked.main.network.umee.cc
rest: https://api.beaked.main.network.umee.cc
watchlist: [
  {
  'name': '',
  'validator_address': '0A123',
  'valoper': 'umeevaloper123'
  },
]
telegram:
  send_message_url: https://api.telegram.org/botXXX:XXX/sendMessage
  chat_id: [XXX, YYY]